[package]
name = "frosty-functions-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.86"
candid = "0.10"
evm_rpc_client = "0.2.0"
evm_rpc_types = "3.0.0"
ic-cdk = "0.18"
ic-cdk-timers = "0.12" # Feel free to remove this dependency if you don't need timers
# TODO: Update
wasmi = { version = "0.35.0", default-features = false }
